rebase-helper/rebase-helper

rebasehelper/archive.py

Added support for .gem files listed as Source0.
Also moved the most common extension matching code to BaseArchive class instead of implementing it in each Archive type. Any type that needs special matching, like ZIP files, can reimplement it.

Added support for .gem files listed as Source0

---

rebasehelper/application.py
rebasehelper/checker.py
rebasehelper/output_tool.py
rebasehelper/utils.py

I'm really not sure how the raising should work, but right now e.g. when merging is not defined in `~/.gitignore`, then we got error like this:
```
('[merge] section is not defined in %s.\n\nOne of the possible configuration can be:\n\n[mergetool 
"mymeld"]\n    cmd = meld --auto-merge --output $MERGED $LOCAL $BASE $REMOTE --diff $BASE
$LOCAL --diff $BASE $REMOTE\n[merge]\n    tool = mymeld\n    conflictstyle = diff3', '/home/hhorak
/.gitconfig')
```
When using `%` instead of more arguments it works better, but maybe the more-arguments style should work as well... Only it doesn't :)

Format error when raising already

---

rebasehelper/checker.py

In case we rebase some non-binary package, rebase helper failed with the following error:
```
Traceback (most recent call last):
File "/home/hhorak/upstreams/github-hhorak/rebase-helper/rebase-helper.py", line 28, in <module>
sys.exit(CliHelper.run())
File "/home/hhorak/upstreams/github-hhorak/rebase-helper/rebasehelper/cli.py", line 138, in run
app.run()
File "/home/hhorak/upstreams/github-hhorak/rebase-helper/rebasehelper/application.py", line 481, in run
self.pkgdiff_packages()
File "/home/hhorak/upstreams/github-hhorak/rebase-helper/rebasehelper/application.py", line 447, in pkgdiff_packages
text = self._execute_checkers(checker)
File "/home/hhorak/upstreams/github-hhorak/rebase-helper/rebasehelper/application.py", line 436, in _execute_checkers
text = …
```

Do not crash if there is no debuginfo package

---

rebasehelper/patch_helper.py
rebasehelper/utils.py

Commit message needs to contain patch name (to be able to map
specific commit to specific patch later), but there is no control
over commit message when applying patches with git am.
This can be worked around by modifying commit message of the latest
commit using git commit --amend.
Closes #109

Amend commit message after applying patches with git am

---

rebasehelper/utils.py

When output of git mergetool is captured, console-based merge tools
(e.g. vimdiff) are not functional, and user is unable to see and respond
to git's interactive propmts.

Do not capture stdout of git mergetool subprocess

---

rebasehelper/application.py
rebasehelper/logger.py

Changes introduced in commit [3820af9](https://github.com/phracek/rebase-helper/commit/3820af9ffe8ff62e76d3afed467bd52d06860fd3) are causing rebase-helper to traceback because of non-existent logger_report in output_tool.py. This PR fixes that.

Fix logging of report from output tools

---

doc-requirements.txt
docs/upstreammonitoring.rst
rebasehelper/application.py
rebasehelper/build_helper.py
rebasehelper/cli.py
rebasehelper/tests/test_cli.py
rebasehelper/utils.py
requirements.txt

This is initial support for Copr as a build tool. It is based on fedpkg implementation, so the usage is similar. For example:
```
rebase-helper --buildtool copr \
--builds-nowait \
--copr-build-ids $OLD_BUILD_ID,$NEW_BUILD_ID \
$NEW_VERSION
```
There are two new dependencies:
- copr (*python-copr* in Fedora)
- pyquery (*python-pyquery* in Fedora)
You will need to get your Copr API token: https://copr.fedorainfracloud.org/api/
Any comments are welcome.
@phracek: Could you test this, possibly with upstream monitoring?

Copr support

---

rebasehelper/application.py
rebasehelper/base_output.py

When running multiple Application instances consecutively,
output data persist between runs and cause results to be incorrect.
Fix that by clearing output data just after Application instance
is created.
This resolves *the-new-hotness* related issue #174.

Clear output data on Application initialization

---

rebasehelper/specfile.py
setup.py

Previously when you failed wo download tarball from Sources you
end up with exception. But I added easy check if tarball exists in
destination_source then it can proceed.
Fixes: #192

Added new feature for tarball downloading

---

rebasehelper/application.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

* Fixed parsing of extra version from some archive names
* Simplified the way we replace Source0 in new SPEC if needed
* Fixed the way we construct Release string when extra version is needed. Now it complies to Fedora Packaging guidelines.
* Resolves issue #144 
It just works :laughing:

Fixed parsing of extra version from some archive names and simplified the way we replace Source0 in new SPEC if needed (resolves issue #144)

---

docs/overview.rst
docs/upstreammonitoring.rst
man/rebase-helper.1
rebase-helper.bash
rebasehelper/application.py
rebasehelper/build_helper.py
rebasehelper/cli.py
workflow.txt

We don't use fedpkg, the option is wrongly named.

Rename fedpkg build tool to koji

---

rebasehelper/specfile.py
rebasehelper/tests/test_utils.py
rebasehelper/utils.py

The `LookasideCacheHelper` class supports both Fedora and RHEL, but downloading from RHEL lookaside cache is functional only in Red Hat internal network. So I didn't enable it in rebase-helper for now. I also marked unit test setup for RHEL lookaside cache as *xfail*, but I can make it run only in case *pkgs.devel.redhat.com* domain is resolvable or remove it completely.
This PR partially resolves issue #198.

Download old sources from Fedora lookaside cache

---

docs/Makefile
docs/archive.rst
docs/autoargs.py
docs/baseoutput.rst
docs/brief-intro.txt
docs/buildloganalyzer.rst
docs/cli.rst
docs/clsoverview.rst
docs/conf.py
docs/custom_man_builder.py
docs/description.rst
docs/exceptions.rst
docs/index.rst
docs/logger.rst
docs/manpage.rst
docs/outputtool.rst
docs/specfile.rst
docs/upstreammonitoring.rst
docs/usage.rst
rebasehelper/cli.py
rebasehelper/specfile.py
rebasehelper/utils.py

This PR adds posibility to automatically generate program documentation from ArgumentParser instance. It introduces Sphinx extension `autoargs`, which is similar to [sphinx-argparse](https://github.com/ribozz/sphinx-argparse), but actually quite different. There is also custom manpage builder `custom-man`, which is needed because default Sphinx manpage builder is not very usable when you want the same source for both html and man.
You can see html output on [readthedocs](http://rebase-helper.readthedocs.io/en/documentation-changes/usage.html).
To see the manpage, run the following in `docs` subdir:
```
make man
man -l _build/man/rebase-helper.1
```
This resolves issue #187.

Documentation changes

---

.gitlab-ci.yml

In Fedora rawhide tox binary moved from python-tox to python3-tox.
Install python3-tox package since doing so won't do any harm on
F23 or F24 and it will prevent test failure on rawhide.

Install python3-tox on Gitlab CI

---

rebasehelper/tests/test_utils.py
rebasehelper/utils.py

Introduce wget-like download progress bar, which can show some statistics also in case the size of downloaded file is not known.
This PR resolves issue #193.
I thought this should be resolved rather sooner than later, since many rebases initiated by upstream monitoring are failing because of this.
@phracek, @thozza: Can you review this PR when you have time?

Do not fail when size of downloaded file is not known

---

rebasehelper/application.py
rebasehelper/build_helper.py

This is necessary for the-new-hotness to be able to pick them up and attach them to bugzilla.

Propagate logs from failed SRPM build to results store

---

rebasehelper/tests/test_utils.py
rebasehelper/utils.py

Starting with fedpkg-1.26, `fedpkg new-sources` uses sha512 hash
for files uploaded to lookaside cache and switches to BSD-style
format of sources file.
Implement support for parsing the new format but remain compatible
with the old format.

Add support for new format of sources file

---

docs/conf.py

Latest koji reads `rpm.__version_info__`, but doing so fails when rpm module is mocked.
Mock also koji module to prevent the failure.

Add koji to the list of mocked modules for sphinx.ext.autodoc

---

rebasehelper/application.py
rebasehelper/build_helper.py
rebasehelper/utils.py

Starting with `koji-1.11.0`, `koji` buildtool is not working anymore.
Make necessary changes to get it working again.

Koji compatibility changes

---

rebasehelper/utils.py

Many git commands fail when `user.name` and/or `user.email` is not configured.
Don't rely on system git configuration (which may not even exist), rather set the values
explicitly on each git call.

Explicitly set git username and e-mail address

---

.gitlab-ci.yml
test-requirements.txt
tox.ini

* Configure Gitlab CI to run tests on F25 instead of F23
* Use fixed version of astroid to make pylint work again (see: https://github.com/PyCQA/astroid/pull/422)
* Set LANG environment variable to make tests UTF-8 aware

Test fixes

---

rebasehelper/checker.py
rebasehelper/checkers/__init__.py
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/checkers/csmock_tool.py
rebasehelper/checkers/pkgdiff_tool.py
rebasehelper/checkers/rpmdiff_tool.py
rebasehelper/tests/base_test.py
setup.py

Checker tools are now defined as entry points in setup.py.
This approach allows anyone to write their own checkers independently on rebase-helper codebase, in their own python package. Here is how setup.py for such package could look like:
```
from setuptools import setup
setup(
name='CustomChecker',
version='0.1',
description='Custom checker tool for rebase-helper',
author='John Doe',
install_requires=['rebase-helper>=0.10.0'],
packages=['custom_checker'],
include_package_data=True,
entry_points={
'rebasehelper.checkers': ['custom_checker = custom_checker:CustomChecker']
}
)
```

Use entry point based approach for checkers

---

rebasehelper/application.py
rebasehelper/spec_hooks/__init__.py
rebasehelper/spec_hooks/typo_fix.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/test.spec
setup.py

Spec hooks are implemented using entry points based approach.
Sample **typo fix** hook and test for it is included.
This PR obsoletes #237.

Implement spec hooks

---

rebasehelper/application.py
rebasehelper/build_helper.py
rebasehelper/build_tools/__init__.py
rebasehelper/build_tools/copr_tool.py
rebasehelper/build_tools/koji_tool.py
rebasehelper/build_tools/mock_tool.py
rebasehelper/build_tools/rpmbuild_tool.py
rebasehelper/cli.py
setup.py

Summary of changes:
* build tools were separated and moved from `build_helper.py` into `build_tools` package
* code from `Application.check_build_requires` was moved to `RpmbuildBuildTool.prepare` method
* build task logic from `Application` was moved to task related methods of **koji** and **copr** build tools
* **koji** build tool is now available only if `koji` module can be successfully imported

Use entry points based approach also for build tools

---

rebasehelper/application.py
rebasehelper/spec_hooks/pypi_url_fix.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/test.spec
setup.py

Transforms https://pypi.* url to https://files.pythonhosted.*
Move downloading of the sources just after the run_spec_hooks,
to allow using the modified sources url.
Obsoletes #223
References #186

Implement pypi_url_fix url hook

---

rebasehelper/application.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

In case `%setup` macro is specified e.g. like this:
`%setup -q -n screen/src`
it means that when rpmbuild is running `%prep`, sources are extracted
to `src` subdirectory.
Switch to such subdirectory after extracting sources, to prevent
patching failures. Also preserve such subdirectories when updating
`%setup` dirname argument.
Add missing newline after updating `%setup` macro.
This PR resolves issue #235.

Handle %setup dirname argument containing slashes

---

Makefile
Makefile.docs
README.md
docs/conf.py

* Entry points need to be accessible also when building documentation for all options to be properly generated.
* Project must be built before generating documentation, otherwise egg-info directory with entry points could be missing or invalid.
* Building man page using `make man` command from project directory now uses **custom-man** builder.
* `backports.lzma` module is no longer being mocked up on readthedocs, as documenation builds were failing because of that.

Fix documentation making

---

doc-requirements.txt

Pull request https://github.com/miyakogi/m2r/pull/3 has been merged, so the original URL is no longer valid.

Update m2r in doc requirements

---

rebasehelper/application.py

Init git repo right after it is created, to catch
version and release changes.
Fixes: #272

Prepare repo right after rebased spec file creation

---

test-deps-fedora.txt

It is needed for `dnf-builddep` plugin (and not installed by default in Fedora rawhide Docker image).

Add missing dnf-plugins-core dependency

---

.gitlab-ci.yml
Makefile.docker
rebasehelper/tests/functional/conftest.py

`mock-1.4.2-1` no longer depends on yum, but it fails to create `/etc/mock/default.cfg` symlink without it, see: https://bugzilla.redhat.com/show_bug.cgi?id=1461839

mock related fixes

---

.gitlab-ci.yml
Makefile.docker

Installing yum updates (lib)curl, but keeps openssl-libs as is, which can trigger this bug in rawhide:
https://bugzilla.redhat.com/show_bug.cgi?id=1462184

Update openssl-libs to workaround curl issue

---

rebasehelper/application.py
rebasehelper/cli.py
rebasehelper/tests/test_cli.py
rebasehelper/utils.py

Added new argument `--get-old-build-from-koji`, only available with **python 2** due to `koji` module still lacking **python 3** support. Hopefully not for long, see: https://pagure.io/koji/c/4f4639ec

Add possibility to download old build from Koji

---

rebasehelper/patch_helper.py
rebasehelper/utils.py

* Do not call git-mergetool using GitPython
* Detect unresolved merge conflicts during interactive rebase

Fixes in rebasing workflow

---

rebasehelper/application.py
rebasehelper/build_tools/koji_tool.py
rebasehelper/tests/test_utils.py
rebasehelper/utils.py

Koji 1.13 finally supports python3, but it's not packaged for Fedora yet, so we should probably wait before merging this.

Update KojiHelper for Koji 1.13

---

rebasehelper/application.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

No need for commenting now, when all changes are already
displayed in the changes patch.
Delete corresponding test.

Delete patch tags of deleted patches from spec file

---

rebasehelper/application.py
rebasehelper/cli.py
rebasehelper/tests/test_cli.py
rebasehelper/tests/test_versioneer.py
rebasehelper/versioneer.py
rebasehelper/versioneers/__init__.py
rebasehelper/versioneers/anitya_versioneer.py
rebasehelper/versioneers/pypi_versioneer.py
requirements.txt
setup.py

Versioneers are tools used for determining latest upstream version of a project.
* `anitya` versioneer queries https://release-monitoring.org
* `pypi` versioneer queries [Python Package Index](https://pypi.python.org/pypi)
This resolves issues #287 and #227.

Implement support for versioneers

---

.gitlab-ci.yml
.travis.yml
Makefile.docker

Fedora 24 is EOL for over a week now and `fedora:latest` points to `fedora:26`.

Replace fedora:24 docker image with fedora:25

---

requirements.txt

This PR is to update `requirements.txt` correctly, and from below conversation.
> https://github.com/rebase-helper/rebase-helper/issues/285#issuecomment-312264180
> it used to be called rpm-python3, we should probably update the comment in requirements.txt

Update a comment for old package rpm-python in requirements.txt

---

Dockerfile
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/checkers/rpmdiff_tool.py
requirements.txt

Fixes #301.
* rpmdiff
* Skip debuginfo and debugsource packages
* Do not traceback when matching new version (sub)package doesn't exist
* abipkgdiff
* Use `split_nevra` from `hawkey` module for reliable parsing of package name
* Find proper debuginfo package for each (sub)package and continue even if it doesn't exist, as abipkgdiff works fine without it - it just shows bare symbols only

Fix rpmdiff and abipkgdiff checkers

---

.gitlab-ci.yml
Makefile.docker

Run tests on Gitlab CI the same way as on Travis CI, using `make test-docker`.

Fix tests on Gitlab CI

---

rebasehelper/specfile.py

`%prep` section can contain long lines split by backslashes. Join such lines before passing them to `shlex.split()`.
Resolves #316.

Fix %prep section parsing

---

rebasehelper/specfile.py

`ArgumentParser.parse_known_args()` is probably buggy, and if there are more short options grouped together and just single one of them is not known, then all the other options are also considered unknown.
`SpecFile.update_setup_dirname()` method depends on `name` (`-n`) option to be present, so this causes unwanted modifications of `%(auto)setup` macro, when e.g. `%setup -qn %{pkgname}-%{version}` is used in a specfile.
Workaround this by adding all currently known options of `%(auto)setup` to the parser.

Add more options to %(auto)setup argument parser

---

Dockerfile
setup.py

I think it's time to add `rpm-py-installer` to install `rpm-python` from pip, as I polished.
https://github.com/junaruga/rpm-py-installer
This fixes https://github.com/rebase-helper/rebase-helper/issues/285 .
I tested installing `rebase-helper` below cases.
```
(venv) $ pip install -e .
(venv) $ pip install .
$ sudo /usr/local/python-3.6.1/bin/pip3 install .
```
How do you think?

Add rpm-py-installer to install rpm-python from pip.

---

.gitlab-ci.yml
.travis.yml
rebasehelper/tests/conftest.py
rebasehelper/tests/functional/conftest.py
rebasehelper/tests/functional/test_rebase.py
tox.ini

Related to https://github.com/rebase-helper/rebase-helper/issues/330#issuecomment-330282635
Now each test has normal, functional or functional_long_running marker. No duplication.
All test = normal + functional + functional_long_running.
marker: normal is default. and run on local.
marker: normal + functional is run in Travis pull-request, and the merge.
marker: normal + functional + functional_long_running (= -m "1") is run on Travis cron mode.
```
$ py.test -m 'normal' --setup-plan rebasehelper | grep "^        rebasehelper/tests" | wc -l
115
$ py.test -m 'functional' --setup-plan rebasehelper | grep "^        rebasehelper/tests" | wc -l
2
$ py.test -m 'functional_long_running' --setup-plan rebasehelper | grep "^        rebasehelper/tests" | wc -l
2
$ py.test -m 1 --setup-plan …
```

Change pytest marker's defintions.

---

tox.ini

With `rpm-py-installer` all required packages can be installed from pip, so this is no longer necessary.

Do not give tox virtualenvs access to sitepackages

---

rebasehelper/specfile.py

`removed_patches` is a class attribute, and as such it persists between instances. So when `Application.run()` is called multiple times in the same script, `removed_patches` can contain data from previous runs, which is undesirable.

Reinitialize removed_patches in SpecFile constructor

---

rebasehelper/application.py

This kind of information is missing in `results_store`.
@skisela: Maybe it could be also displayed in reports, what do you think?

Propagate build errors to results_store

---

rebasehelper/patch_helper.py

Using the class from `git.exc` package is causing pylint to report `no-member` errors.

Use GitCommandError directly from git package

---

setup.py

`rpm-py-installer` is needed only if there is no system rpm distribution available. And since it is not packaged for Fedora, requiring it unconditionally breaks build of rebase-helper Fedora package.

Require rpm-py-installer only if necessary

---

setup.py

This fixes RTD documentation [build](https://readthedocs.org/projects/rebase-helper/builds/6100363/).

Do not require rpm distribution in RTD build environment

---

rebasehelper/utils.py

Related to https://github.com/rebase-helper/rebase-helper/issues/356 .
When the command "pkexec dnf builddep <spec_path>" is run internally in `rebase-helper`, below dialog is appeared. But the text is not user friendly.
```
Authentication Required
Authentication is needed to run `/usr/bin/dnf` as the super user
```
So, I think we need to output log message too.
The message is like this.
```
2017-10-16 06:33:46,308 WARNING utils.py:662 install_build_dependencies: Authentication required to install build depenencies by command 'pkexec dnf builddep /tmp/pytest-of-jaruga/pytest-27/workdir0/libtiff.spec'
```

Add warning log for the command "pkgexec dnf builddep <spec_path>"

---

tox.ini

I want to run specified test case for unit tests.
This feature is beneficial when especially we have to run the case repeatedly such as fixing bug,
`{postargs}` helps the situation.
> http://tox.readthedocs.io/en/latest/example/general.html
> tox -- -x tests/test_something.py
The result is like this.
If the argument is not specified, the default value foo in `{posargs:foo}` is used.
```
$ tox -e py3 -- rebasehelper/tests/test_utils.py::TestConsoleHelper::test_get_message[no]
...
collected 1 item                                                                              
rebasehelper/tests/test_utils.py::TestConsoleHelper::test_get_message[no] PASSED
================================== 1 passed in 0.22 seconds ==================================
__________________________________________ …
```

Run unit tests for specified test file and the case.

---

rebasehelper/application.py
rebasehelper/cli.py
rebasehelper/specfile.py
rebasehelper/tests/test_cli.py
rebasehelper/tests/test_specfile.py

Resolves: #353 
Custom changelog entry can be set using --changelog-entry "message". RPM macros can be used to add version and other things (%{version}, %{name} etc.)
```
[root@9af0720655ba rubygem-afm]# python3 ../rebase-helper/rebase-helper.py --changelog-entry "Update to {VERSION}"
...
[root@9af0720655ba rubygem-afm]# diff rubygem-afm.spec rebase-helper-results/rebased-sources/rubygem-afm.spec
6c6
< Release: 6%{?dist}
---
> Release: 1%{?dist}
74a75,77
> * Tue Oct 17 2017 rebase-helper <rebase-helper@localhost.local> - 0.2.2-1
> Update to 0.2.2
```
@junaruga Which other options of formating would you like to have?

Add changelog template

---

Makefile
rebase-helper.bash.in
rebasehelper/cli.py

* Clean up before running `test-docker` make target
* Fix variable name in `rebase-helper.bash.in`
* Remove redundant dest argument of `--color` option

Minor fixes

---

rebasehelper/application.py

If local version is higher than (or equal to) the latest upstream version, rebase-helper doesn't do anything.
For example:
```
[root@9af0720655ba rubygem-afm]# python3 ../rebase-helper/rebase-helper.py 
Results directory 'rebase-helper-results' exists, removing it
Workspace directory 'rebase-helper-workspace' exists, removing it
Running 'rubygems' versioneer
Determined latest upstream version '0.2.2'
Your current version is the latest available version.
```
Resolves: #354

Compare local and the latest upstream version

---

rebasehelper/tests/functional/test_rebase.py

This fixes https://github.com/rebase-helper/rebase-helper/issues/356 .
This PR is inspired from https://docs.pytest.org/en/latest/skipping.html .
> def test_function():
>     if not valid_config():
>         pytest.skip("unsupported configuration")
The result is like this.
```
$ whoami
jaruga
$ tox -e py3 -- -m 1 rebasehelper/tests/functional/test_rebase.py
...
rebasehelper/tests/functional/test_rebase.py::TestRebase::test_rebase[vim-go-1.11-2=>1.12-rpmbuild] SKIPPED
rebasehelper/tests/functional/test_rebase.py::TestRebase::test_rebase[vim-go-1.11-2=>1.12-mock] PASSED
rebasehelper/tests/functional/test_rebase.py::TestRebase::test_rebase[libtiff-4.0.7-5=>4.0.8-rpmbuild] SKIPPED
rebasehelper/tests/functional/test_rebase.py::TestRebase::test_rebase[libtiff-4.0.7-5=>4.0.8-mock] PASSED …
```

Update to skip rpmbuild test when it is run by non-root user.

---

rebasehelper/tests/test_utils.py
rebasehelper/utils.py

This fixes https://github.com/rebase-helper/rebase-helper/issues/352
I added warnings for the case of failure to get user and email.
I added very simple unit tests.
```
(venv) $ rebase-helper
(venv) $ diff rubygem-byebug.spec rebase-helper-results/rebased-sources/rubygem-byebug.spec
126a127,129
> * Wed Oct 18 2017 Jun Aruga <jaruga@redhat.com> - 9.1.0-1
> - New upstream release 9.1.0
>
```
```
(venv) $ rebase-helper
...
Faild to get Git user.name. Return the fallback value 'rebase-helper'
Faild to get Git user.email. Return the fallback value 'rebase-helper@localhost.local'
...
Faild to get Git user.name. Return the fallback value 'rebase-helper'
Faild to get Git user.email. Return the fallback value 'rebase-helper@localhost.local'
...
(venv) $ diff rubygem-byebug.spec …
```

Fix to get git config user.name and user.email correctly.

---

rebasehelper/application.py
rebasehelper/build_helper.py
rebasehelper/build_tools/copr_tool.py
rebasehelper/build_tools/koji_tool.py
rebasehelper/build_tools/mock_tool.py
rebasehelper/build_tools/rpmbuild_tool.py
rebasehelper/cli.py
rebasehelper/srpm_build_tools/__init__.py
rebasehelper/srpm_build_tools/mock_tool.py
rebasehelper/srpm_build_tools/rpmbuild_tool.py
rebasehelper/tests/test_cli.py
setup.py

Pass builder_options values to `build_dict{}`
Implement `SRPMBuilderTools` to allow users to use mock for source rpms creation.
Implement `SRPM options` to allow users to set configuration for building source rpms.
Resolves: #366 #361

Create SRPM builder tools

---

.gitlab-ci.yml
.travis.yml
Makefile.docker

`fedora:latest` now points to F27, so it is time to move from `fedora:25` to `fedora:26`.

Run tests on F26, F27 and rawhide

---

rebasehelper/application.py

When the exception was raised, it resulted in an error: "not enough arguments for format string" because of the missing parentheses

Add parentheses to format error message properly

---

rebasehelper/application.py

Add parentheses to format the error message properly

---

rebasehelper/cli.py
rebasehelper/config.py
rebasehelper/constants.py
rebasehelper/options.py
rebasehelper/tests/functional/test_rebase.py
rebasehelper/tests/test_application.py
rebasehelper/tests/test_conf.py

There is now a parameter --conf to set path to a configfile.
If the path is not set, $HOME/.config/rebase-helper is used by default.
Config lines starting with # are ignored.
CLI arguments have priority over config arguments if they are set manually.
If there is not a certain config argument, CLI argument is used.
Resolves: #294

Merge CLI arguments with config arguments

---

Dockerfile

Add `@development-tools` to Dockerfile dependencies as `make` is part of it.
`make` is not installed as a dependency of the other packages, while being needed by packages that are tested in https://github.com/rebase-helper/rebase-helper/commit/176daef0fa215850af27dbce173912a3ae643585#diff-6d588bc259cac6db1bdba0eac89f42d5R35

Fix failing test on F26 due to missing make

---

rebasehelper/sample_config.py

Resolves: #369.
Generated config file currently looks like this:
```ini
[general]
verbose = False
color = auto
results-dir = 
patch-only = False
build-only = False
comparepkgs-only = False
continue = False
buildtool = mock
srpm-buildtool = rpmbuild
pkgcomparetool = rpmdiff,abipkgdiff,pkgdiff
outputtool = text
versioneer = 
non-interactive = False
not-download-sources = False
keep-workspace = False
disable-inapplicable-patches = False
get-old-build-from-koji = False
skip-version-check = False
builds-nowait = False
build-tasks = 
builder-options = 
srpm-builder-options = 
changelog-entry = - New upstream release %{version}
```
@skisela, @FrNecas: Any thoughts? What else to blacklist for instance...

Generate sample config file

---

rebasehelper/archive.py
rebasehelper/specfile.py
rebasehelper/tests/test_archive.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/archive-invalid.tar.bz2
rebasehelper/tests/testing_files/archive-invalid.tar.xz
rebasehelper/tests/testing_files/test.spec

* Handle exceptions while opening archive
- resolves #383
* Handle whitespace before colon in tag definitions
- resolves #387
* Escape source string before constructing regexp from it
- resolves #388
* Handle mixed-case spec sections
- resolves #389

Multiple fixes

---

.travis.yml

It is no longer necessary as installed docker version is now `17.09.0-ce`.

Stop updating docker on Travis

---

rebasehelper/tests/test_utils.py

`fake_IO` fixture is not working as expected, because pytest overwrites `sys.stdout` and `sys.stderr` after it is called.
Use `monkeypatch` to replace **stdin** and `capsys` to capture **stdout** instead.

Fix TestConsoleHelper.test_get_message() test

---

rebasehelper/utils.py

_stream=True_ was missing, so the file was not downloaded continuously and progress bar immediately jumped to 100%.
Resolves: #411

Fix progress bar for downloading from http

---

rebasehelper/utils.py
setup.py

Download progress is not indicated properly with FTP transfers because stream mode is not supported in `requests_ftp`.
Implement custom urllib-based `FTPAdapter` instead.
Resolves #413.

Use custom requests adapter instead of requests_ftp

---

pylintrc
tox.ini

Landscape.io does checks based on pylintrc, and we want to see all the problems.

Move pylint exclusions from pylintrc to tox.ini

---

rebasehelper/application.py
rebasehelper/utils.py

Base Exceptions are very non-informative when building packages. We should consider logging the errors into debug log.
Fixes: #376

Handle SSL Exception when kerberos ticket is missing

---

rebasehelper/application.py
rebasehelper/build_helper.py
rebasehelper/build_tools/koji_tool.py
rebasehelper/build_tools/mock_tool.py

As mentioned in https://pagure.io/koji/issue/712 getTaskResult raises exception which contains koji error message, in case the build failed.

Get error from koji and process it

---

rebasehelper/spec_hooks/commit_hash_updater.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/test.spec
setup.py

`CommitHashUpdaterHook` tries to update commit hash present in `Source0` tag according to the new version.
Only `github.com` is supported so far via [Github API](https://developer.github.com/v3/). But it seems majority of packages using commit hashes are Github based.
Resolves: #372

Add CommitHashUpdater SPEC hook

---

rebasehelper/application.py
rebasehelper/build_helper.py
rebasehelper/build_tools/copr_tool.py
rebasehelper/build_tools/koji_tool.py
rebasehelper/build_tools/mock_tool.py
rebasehelper/build_tools/rpmbuild_tool.py
rebasehelper/srpm_build_tools/mock_tool.py
rebasehelper/srpm_build_tools/rpmbuild_tool.py

This PR splits build process into two phases, build of source packages (SRPM) and build of binary packages (RPM).
This is necessary for SRPM checkers to be able to run just after SRPMs are built.
Also now one doesn't have to wait until all old-version RPMs are built only to find out there is some trivial error in rebased SPEC file and new-version SRPM build fails because of that.

Refactor build process

---

rebasehelper/archive.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/test.spec
rebasehelper/utils.py

* Add uncompressed tar to supported archive types (fixes #455)
* Do not use default error handler of ArgumentParser
* Fix testing spec file

Several fixes

---

docker/Dockerfile.base
docker/getkey.sh

Before beta freeze of a Fedora release it can happen that some packages are already signed with a GPG key of that release, but the key is not yet installed as part of fedora-repos package.
Try to download and install such key from upstream repository in base image to prevent installation failures.

Get potentially missing package signing key

---

rebasehelper/cli.py
rebasehelper/logger.py
rebasehelper/options.py
rebasehelper/output_tool.py
rebasehelper/tests/test_utils.py
rebasehelper/utils.py
setup.py

Colorize console output using ColorizingStreamHandler.
Also, use formatter to display logging level in the output.
There are now 2 color maps, they can be either switched manually or rebase-helper can decide which one to use depending on the background color of the terminal.
4 new logging levels have been added 
- SUCCESS for successful operations (colored to green)
- HEADING for separating individual sections of output ( colored to blue/yellow)
- IMPORTANT to highlight important messages (colored to red)
- TRACE to differentiate between traceback and debug messages (colored to red)

Enhance console logging

---

rebasehelper/options.py

It doesn't make sense to have `--results-dir` between `--color` and `--background`. Also the description needed tweaking.

Adjust --background option

---

rebasehelper/application.py
rebasehelper/options.py
rebasehelper/tests/functional/test_rebase.py

After a successful rebase, there is now a possibility to apply the `changes.patch` as a commit to the `dist-git`.
Implements one of the steps towards complete automation mentioned in #462.

 Add CLI option for applying changes patch

---

rebasehelper/checker.py
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/checkers/csmock_tool.py
rebasehelper/checkers/licensecheck_tool.py
rebasehelper/checkers/pkgdiff_tool.py
rebasehelper/checkers/rpmdiff_tool.py

ABIPkgDiff now writes numbers from all detected ABI changes.
Example:
```
abipkgdiff
==========
ABI changes in pstoedit:
- libp2edrvstd.so.0.0.0 - Functions changes summary
- Changed 1 (filtered out 66)
- Removed 0 (filtered out 14)
- libpstoedit.so.0.0.0 - Functions changes summary
- Added 3 (filtered out 2)
- Changed 2 (filtered out 51)
- Removed 1 (filtered out 10)
- libpstoedit.so.0.0.0 - Variables changes summary
- Changed 1 (filtered out 3)
- libp2edrvwmf.so.0.0.0 - Functions changes summary
- Changed 1 (filtered out 2)
- libp2edrvlplot.so.0.0.0 - Functions changes summary
- Changed 1 (filtered out 2)
- Removed 0 (filtered out 2)
Details in rebase-helper-results/checkers/abipkgdiff:
- pstoedit.txt
- pstoedit-devel.txt
```
Fixes #489

Fix ABIPkgDiff report file generation

---

rebasehelper/application.py
rebasehelper/options.py
rebasehelper/patch_helper.py
rebasehelper/tests/functional/test_rebase.py

"git rebase" --strategy-option makes use of prefering one or the other
sides that are being merged.
"upstream" in context of rebase-helper rebasing refers to the upstream code,
while "downstream" refers to the downstream code(with the downstream patches).
https://git-scm.com/docs/git-rebase#git-rebase--Xltstrategy-optiongt

Enable --strategy-option for rebasing

---

rebasehelper/build_helper.py
rebasehelper/checker.py
rebasehelper/cli.py
rebasehelper/constants.py
rebasehelper/options.py
rebasehelper/output_tool.py
rebasehelper/specfile.py
rebasehelper/versioneer.py

It is necessary to list all argument choices when generating documentation, bash completion data or sample configuration.
List all argument choices by default, and list just those available only when running rebase-helper directly.

Default to listing all argument choices, list available only on request

---

Makefile
rebase-helper.py

Starting with Fedora 29, there is no unversioned `python` command installed by default. There is no real reason not to use `/usr/bin/python3` instead of `/usr/bin/python`.

Get rid of unversioned python command

---

rebasehelper/application.py
rebasehelper/helpers/lookaside_cache_helper.py
rebasehelper/options.py

There is no need to upload sources to lookaside cache again if one wants to *replay* past rebase.

Add --skip-upload option

---

rebasehelper/specfile.py

`%prep` section is not mandatory and doesn't have to be present in a spec file. Handle such case.

Handle missing %prep section

---

rebasehelper/spec_hooks/ruby_helper.py

Introduction of `SpecContent` removed newlines from line items, so they need to be added when generating a script.

Fix ruby-helper spec hook

---

rebasehelper/specfile.py

* Prevent expansion of `%autosetup` macro
* Handle multiline macros and shell expansions
* Implement parsing of shell expansions

SpecFile fixes

---

docker/Dockerfile.webhooks
docker/webhooks.py

This image serves as a [release event](https://developer.github.com/v3/activity/events/types/#releaseevent) webhook enpoint and automatically publishes new releases on PyPI.

Add container image serving as GitHub release webhook endpoint

---

rebasehelper/tests/test_helpers.py

This makes pytest work on real systems with existing git configuration.

Prevent existing $HOME/.gitconfig from being read in TestGitHelper

---

.packit.yaml
rebase-helper.spec

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>
This PR adds support for packit https://github.com/packit-service/packit, which syncs upstream changes into downstream automatically. See docu on packit side https://github.com/packit-service/packit/blob/master/README.md.

Add support for packit

---

rebasehelper/tests/test_output_tool.py

Checkers were absent in the test report due to results_store being wrong.

Fix TestOutputTool for checkers

---

rebasehelper/build_tools/koji_tool.py
rebasehelper/helpers/koji_helper.py

Downloading builds and logs from Koji, as well as querying task info doesn't require login. Don't attempt to log-in in such cases, to allow users without FAS to use `--get-old-build-from-koji` option.
Fixes #567.

Only attempt Koji login if necessary

---

rebasehelper/application.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

Changelog_entry isn't now passed into the constructor of a SpecFile which should make it more logical to use.
Any objections @TomasTomecek , does this suit your use-case better?

Refactor how adding changelog entries works

---

rebasehelper/build_log_hooks/files_build_log_hook.py
rebasehelper/spec_hooks/commit_hash_updater.py
rebasehelper/spec_hooks/escape_macros.py
rebasehelper/spec_hooks/paths_to_rpm_macros.py
rebasehelper/spec_hooks/pypi_url_fix.py
rebasehelper/spec_hooks/replace_old_version.py
rebasehelper/spec_hooks/ruby_helper.py
rebasehelper/spec_hooks/typo_fix.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

Sections in a spec file can be enclosed in conditions, which means they can be duplicate.
Use list of tuples instead of dict to store them.

Do not use dict to store spec sections

---

rebasehelper/helpers/rpm_helper.py
rebasehelper/specfile.py

Future rpm versions will return unicode instead of bytes in python 3.
Account for that in a new wrapper method.

Properly handle text data from rpm module

---

rebasehelper/application.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

Only Application makes use of this argument. The value can be accessed
from configuration taken from CLI/config file.

Remove 'download' argument from SpecFile's constructor

---

rebasehelper/exceptions.py
rebasehelper/helpers/rpm_helper.py
rebasehelper/specfile.py

Parsing errors from rpm were supposed to be logged, but that didn't happen in case of exception handling (so basically never).
Fix that and instead of logging the errors using logger, include them in the raised exception instance to make it more convenient.

Fix capturing rpm output and include it in exception

---

.packit.yml

We are working on a next release of packit where we'll finally implement jobs.
Our current plan is to change the schema, which means that future version of
packit would fail parsing this config file.
This PR therefore removes content from packit.yml which packit does not even
process now.

packit.yaml: drop unused content

---

setup.py

Branch name was missing so the link could never work, as it defaults to **master**, which doesn't contain the change.
According to [PEP 508](https://www.python.org/dev/peps/pep-0508/), it is possible to specify an URL in `install_requires` directly, no need for `dependency_links`.

Fix ansicolors dependency

---

rebasehelper/plugins/output_tools/__init__.py
rebasehelper/plugins/output_tools/text.py

If a checker is not supported, `check_tool` is set to  None and it results
in AttributeError.

Fix printing of checker output for unsupported tools

---

rebasehelper/specfile.py

Ignore unmatched quotation characters in comments.

Fix determining unmatched quotation in %prep section

---

rebasehelper/specfile.py

Patch can appear "unused" for instance if it's conditionalized and the condition evaluates to false, but that doesn't mean such patch should be removed, as in a different context it could be valid, and removing
the corresponding Patch tag would render the package unbuildable.

Do not remove "unused" patches

---

rebasehelper/helpers/macro_helper.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

`rpm.reloadConfig()`, among other things, resets all macros to default values and removes previously defined macros. That should prevent issues with polluted global macro namespace when parsing multiple different SPEC files.

Use rpm.reloadConfig() before parsing SPEC

---

rebasehelper/application.py

Printing lists or dict keys is not very user friendly (`Supported archives are dict_keys(['.tar.xz', ...])` vs `Supported archives are .tar.xz, .bz2, ...`). Also fix a bug in Application, where an incorrect method of PluginCollection was called to get supported tools.

Format output lists in a more readable way

---

rebasehelper/plugins/build_tools/__init__.py
rebasehelper/plugins/build_tools/rpm/mock.py
rebasehelper/plugins/build_tools/srpm/mock.py
setup.py

`mock` uses `userhelper` to get superuser permissions, but `userhelper` doesn't support non-interactive use.
Run `mock` using `pkexec` wrapper if (and only if) `userhelper` would need to ask for a password.
Fixes #636.

Prevent mock (userhelper) from asking for a password

---

rebasehelper/plugins/spec_hooks/replace_old_version.py

Without the special case, version format changes resulted in a wrong
correction. For example in rebase from 2.5 to 2.5.1, the Version tag
would be changed to 2.5.1.1.
Resolves: #643

Special case Version tag in ReplaceOldVersion hook

---

rebasehelper/application.py
rebasehelper/helpers/koji_helper.py

In `golang-github-google-cmp` rebase from 0.2.0 to 0.3.0, the old build wasn't in koji, whereas the new one was. rebase-helper couldn't handle such thing. What we should also consider is changing `KojiHelper.get_old_build_info()`. Currently if the old version build can't be obtained, it fallbacks to getting the latest build. Since this method is used only when `--get-old-build-from-koji` is active, it imho doesn't make much sense (we want the old build or nothing, getting the info about new build is pointless). What's your opinion @nforro ? Is there any case, where the fallback could be useful?

Use local builder when the build can't be downloaded from koji

---

rebasehelper/helpers/lookaside_cache_helper.py

Sorry, somehow this slipped my attention yesterday and I unfortunately tested the functionality on a package, which wasn't uploaded to lookaside cache :(

Fix a bug in LookasideCacheHelper

---

rebasehelper/patcher.py

GitPython 3.0.0 was released and this workaround is no longer needed.

Remove GitPython bug workaround

---

docker/Dockerfile.webhooks
setup.py

`setuptools_scm` and `setuptools_scm_git_archive` are required for `setup.py` to run, so they need to be listed in `setup_requires`, not `install_requires`.

 Move setup dependencies to setup_requires

---

docker/Dockerfile.webhooks

I hope this will prevent the incomplete output issue.

Disable stdout/stderr buffering in release webhook

---

docs/user_guide/logging.rst
rebasehelper/application.py
rebasehelper/cli.py
rebasehelper/logger.py

Fixes #684.
I decided not to implement `cleanup()` method, because it is necessary to remember the created handler instances, and since their lifetime matches the lifetime of `Application` instance, creating them in its constructor and removing them in its destructor makes more sense.

Remove automatically created logging file handlers

---

.gitignore

After installing setuptools-scm using pip,  `.eggs` directory appeared in the root of my git repo.

Add .eggs directory to gitignore

---

rebasehelper/application.py

Building could fail due to other reasons than just rpmbuild/mock failure.
Copr config could be missing or Koji authentication can fail. Inform the
user even in such cases about what went wrong.

Always log the reason of build failure

---

rebasehelper/application.py
rebasehelper/helpers/rpm_helper.py
rebasehelper/plugins/build_tools/rpm/rpmbuild.py
rebasehelper/plugins/checkers/abipkgdiff.py
rebasehelper/plugins/checkers/pkgdiff.py
rebasehelper/plugins/checkers/rpmdiff.py
rebasehelper/plugins/checkers/sonamecheck.py
rebasehelper/plugins/spec_hooks/commit_hash_updater.py
rebasehelper/plugins/spec_hooks/replace_old_version.py
rebasehelper/plugins/spec_hooks/ruby_helper.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

I decided to keep `SpecFile.get_version()` in order not to break `packit`.

Use RpmHeader helper class to access package header attributes

---

rebasehelper/application.py
rebasehelper/helpers/rpm_helper.py
rebasehelper/plugins/spec_hooks/ruby_helper.py
rebasehelper/specfile.py

Move spec-related stuff to `RpmHelper.get_rpm_spec()`, it doesn't work properly without it anyway.
Introduce public `SpecFile.update()` method and use it instead of `SpecFile._update_data()` everywhere except in `SpecFile` constructor.
Fixes #710.

Refactor SpecFile._update_data()

---

rebasehelper/specfile.py

Example case that doesn't work properly without this fix: `1%{?dist}` ⇒ `1.1%{?dist}`

Fix replacing tags while preserving macros

---

rebasehelper/patcher.py

This should prevent rebase-helper dying on files which have non-utf8 characters in them.
```
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/rebasehelper/cli.py", line 128, in run
app.run()
File "/usr/lib/python3.7/site-packages/rebasehelper/application.py", line 802, in run
self.patch_sources([old_sources, new_sources])
File "/usr/lib/python3.7/site-packages/rebasehelper/application.py", line 421, in patch_sources
**self.kwargs)
File "/usr/lib/python3.7/site-packages/rebasehelper/patcher.py", line 329, in patch
return cls._git_rebase()
File "/usr/lib/python3.7/site-packages/rebasehelper/patcher.py", line 207, in _git_rebase
if [l for l in f.readlines() if '<<<<<<<' in l]:
File "/usr/lib64/python3.7/codecs.py", line 322, in decode
(result, consumed) = …
```

patcher: check for merge conflicts in binary mode

---

rebasehelper/application.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/rebase/test.spec

This should fix rebasing from pre/post-release to a stable release, and from pre/post-release to a different pre/post-release. Rebasing from stable release to pre/post-release most likely requires modifying `Source0` tag, which is currently not implemented.

Make extra version mostly work

---

rebasehelper/specfile.py

* **Do not consider URL to be a commented-out tag**
It's quite common to add comments with e.g. bugzilla URLs before `Patch` tags in a SPEC. These should of course be removed when removing the tag. Enhance the tag pattern not to match `http(s)://`.
* **Reintroduce `SpecFile.set_release_number()` for backward compatibility**
This method is used by packit, so keep it, although the name is not accurate.

More SpecFile fixes

---

.travis.yml
docker/Dockerfile.base

Since `stat` now uses `statx` syscall, it is necessary to run tests with docker version incorporating  https://github.com/moby/moby/pull/36417.
Also, `python3` defaults to `python38` on rawhide, so `python37` is missing and needs to be installed explicitly.

Fix Travis tests

---

rebasehelper/plugins/spec_hooks/replace_old_version.py
rebasehelper/specfile.py
rebasehelper/tags.py
rebasehelper/tests/test_tags.py

As even Source and Patch tags can be in different sections than preamble, it makes more sense to default to all sections.

Default to all sections in Tags.filter()

---

rebasehelper/plugins/spec_hooks/commit_hash_updater.py

Example of a problematic release: https://api.github.com/repos/KhronosGroup/glslang/releases/15961606 (caused traceback in batch rebase)

Handle null release name in CommitHashUpdater

---

rebasehelper/plugins/spec_hooks/replace_old_version.py
rebasehelper/spec_content.py
rebasehelper/specfile.py
rebasehelper/tags.py
rebasehelper/tests/public_api/test_tags.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/test_tags.py

Related: #622 (this just implements parsing)
This just adds parsing support, integration with other parts of rebase-helper may not be perfect. For example if rebase-helper removes a patch from preamble and `%patchlist` is present and the patches are applied in `%prep` using `%patch` macro, it is going to break. But I think this deserves its own issue/PR.
Also, I haven't found a way how to support conditionalized sources in `%sourcelist` or `%patchlist`. Say the section looks like this:
```
%sourcelist
source2.tar.gz
%if 0%{?source:1}
source3.tar
%endif
```
I don't think there is a consistent way to differentiate between the source and the `%if` macro (neither are in parsed spec object).

Implement parsing of %sourcelist and %patchlist

---

rebasehelper/plugins/checkers/pkgdiff.py
rebasehelper/tests/plugins/test_output_tools.py

* Fix SyntaxWarning due to comparison of literals using is.
```
find . -iname '*.py'  | xargs -P 4 -I{} python3.8 -Wall -m py_compile {}
./rebasehelper/plugins/checkers/pkgdiff.py:119: SyntaxWarning: "is" with a literal. Did you mean "=="?
if old_version is '':
./rebasehelper/plugins/checkers/pkgdiff.py:123: SyntaxWarning: "is" with a literal. Did you mean "=="?
if new_version is '':
```
* Remove deprecated encoding parameter used in `json.load` for Python 3.9 .
Fixes #770

Add Python 3.9 compatibility.

---

rebasehelper/specfile.py

Always use base names when working with patches

---

rebasehelper/specfile.py

The SpecContent instance which _read_spec_content() returns
is thrown away so the call is useless.
update() calls it too, but saves the instance to self.spec_content

[SpecFile.reload()] don't _read_spec_content() before update()

---

rebasehelper/patcher.py

As opposed to normal merge conflicts, deleted merge conflicts can be resolved by deleting a file.
Account for such case.
Example:
```
Normal merge conflict for 'doc/fixinfo.sh':
{local}: modified file
{remote}: modified file
4 files to edit
Deleted merge conflict for 'doc/groff.info-2':
{local}: deleted
{remote}: modified file
Use (m)odified or (d)eleted file, or (a)bort? d
```

Skip deleted files when detecting unresolved conflicts

---

.packit.yml
rebasehelper/tags.py

When I was debugging some rebase-helper related code I needed to see tags values, so I added this `Tag.__str__()`.
This PR also removes `specfile_path` from `.packit.yml` to verify that the problem we saw in https://github.com/rebase-helper/rebase-helper/pull/785#issuecomment-593292961 is fixed.

Add Tag.__str__()

---

rebasehelper/patcher.py

Since git switched its rebase backend from apply to merge, it launches a commit message editor on `git rebase --continue`. This causes **rebase-helper** to hang indefinitely.
Prevent that from happening by explicitly reconfiguring the editor in the git repo.

Prevent git commands from launching an interactive editor

---

rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

RPM allows the use of tilde in Version tag. Moreover, the Fedora
Packaging Guidelines mention tilde as a possible way of specifying
prereleases. See the following link for more information:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/

Allow tilde as extra version separator

---

rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

This is mainly a cosmetic change to avoid leaving 2 or more blank lines
in the specfile after removing a patch that is surrounded by blank
lines.

Remove excessive blank lines when removing patches

---

rebasehelper/application.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

Names of local Sources and Patches may change between 2 versions (for example when %{version} macro is used in their names). This could lead to a failed rebase, SRPM build will fail.
Try to handle the situation by renaming the patches and sources in rebased-sources directory, changing their paths in specfile and then reverting the names back.

Rename sources and patches if necessary

---

containers/Makefile.podman

Since containters in a pod do not share network namespace by default anymore, create a pod explicitly configured to do that.
Also, as `SYS_ADMIN` capability doesn't seem to be enough for mock anymore, run the tests container in privileged mode.
Use long options everywhere for clarity.

Make test-podman work again

---

rebasehelper/tests/functional/test_rebase.py
rebasehelper/tests/testing_files/rebase/test.spec

Incorporating the test for the new feature into the existing test turned out to be easier than I expected. I can't think of any other use cases that would need to be tested, so it isn't necessary to create a separate test (at least for now)
Resolves: #807

Add a test for patch renaming

---

rebasehelper/specfile.py

We (https://github.com/packit/) hit the [issue](https://github.com/packit/dist-git-to-source-git/issues/72) with macros being modified when creating srpm's on converted source-git repositories. We have a [workaround](https://github.com/packit/packit/pull/970) but crave for cleaner solution :)

Allow turning off macro preserving in set release or version

---

rebase-helper.spec
rebasehelper/application.py
rebasehelper/plugins/checkers/rpminspect.py

* Do not retry build when a checker fails
* Explicitly specify config file path for rpminspect (see Fedora bug [#1881909](https://bugzilla.redhat.com/show_bug.cgi?id=1881909)).

Fix rpminspect checker

---

rebasehelper/application.py

It is expected that build dict contains a single SRPM per build, but `KojiHelper.download_build()` returns a list of packages. Fix that.
Fixes: #825

Fix updating build dict when getting old build from Koji

---

rebasehelper/plugins/build_tools/rpm/koji_.py

It doesn't make sense to do builds on all architectures, since **rebase-helper** currently only supports *x86_64*.

Limit koji buildtool to a single architecture

---

rebasehelper/helpers/macro_helper.py
rebasehelper/tags.py

Errors are expected, for example when trying to expand a single line of a multiline macro, but they are not useful and should be ignored.
Fixes #833.

Suppress errors when expanding macros during parsing of tags

---

rebasehelper/tests/public_api/test_tags.py

Since Python 3.10, Iterator must be imported from collections.abc rather than collections.
The issue isn't present in any other module, as the only thing we use from collections (aside from `Iterator`) is `defaultdict` which isn't affected by the deprecation.

Fix collections deprecation in test_tags

---

rebasehelper/helpers/lookaside_cache_helper.py
rebasehelper/tests/helpers/test_lookaside_cache_helper.py

Majority of supported lookaside cache servers currently don't handle chunked POST requests properly, so special-case the only one that does. Also, always try to use opportunistic SPNEGO authentication first, to avoid having yet another special case.

Change approach to lookaside cache servers

---

rebasehelper/specfile.py
rebasehelper/tests/public_api/test_specfile.py
rebasehelper/tests/test_specfile.py

Having the wrong locale running on your machine shouldn't
result in a changelog with invalid syntax or foreign characters.
Example of a bad date here:
https://src.fedoraproject.org/rpms/oci-kvm-hook/pull-request/2#request_diff
Technically setlocale() is not threadsafe. However it is unclear
whether this is a problem for rebase-helper. If it is a problem,
then we must replace strftime() usage in order to fix this problem.
The test aims to be reproducible, despite every system having all
sorts of different locales installed.

Use C locale for updating %changelog

---

containers/Containerfile
containers/Containerfile.base.fedora-latest
containers/Containerfile.base.fedora-rawhide

`test_get_new_log_with_non_c_locale` requires at least one non-English locale to be able to actually test anything, since there is only C locale in Fedora container images.
Also make rebase-helper container use image from quay.io.

Add glibc-langpack-de to base images

---

containers/Containerfile.base.fedora-latest
containers/Containerfile.base.fedora-rawhide

Automatic builds on quay.io seem to have trouble pulling Fedora images from the default registry (presumably docker.io). This should solve it.

Use Fedora registry for Fedora images

---

rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/test.spec

Resolves: https://github.com/rebase-helper/rebase-helper/issues/855
Tried on the repo @TomasTomecek linked in the issue and it seems to work correctly now (also added a test that struggled from the same problem)
Previously, the regular expression for finding macro definitions didn't
correctly consider the possibility of having multiple macros inside
value of a macro (e.g. %{major}.%{minor}) resulting in incorrect value
parsing in some cases where macro definitions ended with regular string
characters as found in the following reproducer:
%global general_version %{pybasever}.5
#global prerel ...
%global upstream_version %{general_version}%{?prerel}
The value of 'general_version' macro would previously span across all
three lines due to greedy matching and re.DOTALL which resulted in …

Fix macro value detection in set_tag

---

rebasehelper/plugins/checkers/licensecheck.py

Since version 3.2.0, `licensecheck --help` exits with 1 instead of 0. Switch to `licensecheck --version` that seems to have consistent exit code.

Fix licensecheck availability test

---

containers/docker-compose.yml

Without making it privileged, tests using mock fail in Github Actions.
This used to work in Travis CI but apparently Github uses a newer OS or
docker version.
This fixes the behaviour, see https://github.com/rebase-helper/rebase-helper/actions/runs/1026615062

Make container with tests privileged

---

rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

there can be spec files which are meant to define dependencies only thus
they ship no files and have no sources
Please let me know where should I create a test case.
https://sentry.io/share/issue/1e27f7ad5acd49c29f2c27957741ebb4/

spec: sources may not be defined

---

rebasehelper/plugins/checkers/rpmdiff.py

It seems there is a bug in rpmdiff argument parsing, however long options still work correctly, and they are more verbose, so just use them.

Use long options with rpmdiff

---

rebasehelper/patcher.py

Default branch name can be anything, it's no longer "master", so avoid referencing it by name.
Fixes #874.

Replace hardcoded references to master

---

.github/workflows/ci.yml

It seems the workaround is no longer necessary, and functional tests fail with outdated base images, so it's time to move on.

Remove workaround for docker in Github Actions

---

.packit.yml

...during the CI builds
Resolves: https://github.com/packit/packit/issues/1520
The problem is that a macro `%dump` which comes from a commit title is
interpreted and makes the spec unparsable.

packit: use bumpspec to update spec

---

rebasehelper/patcher.py

Some tarballs contain additional git metadata such as submodule config.
If it exists and submodules are not checked out, certain GitPython functions traceback. Avoid that.

Remove any existing submodule configuration before rebasing

---

pylintrc
rebasehelper/helpers/console_helper.py
rebasehelper/patcher.py
rebasehelper/specfile.py

RPM >= 4.18 uses *rpmuncompress* rather than calling *tar* or *unzip* directly. Account for that in `SpecFile.find_archive_target_in_prep()`.
Solves FTBFS in Fedora Rawhide.

Add support for rpmuncompress

---

rebasehelper/patcher.py

`git-rebase` exits with code 128 in case of an unexpected error. Raise an exception in such case, to prevent endless loop or some other undefined behavior, and log the exact git command and the error message.
Related to #891.

Handle unexpected git-rebase errors

---

rebasehelper/plugins/checkers/sonamecheck.py

debuginfo packages can provide a shared library, but it doesn't actually have a SONAME. Just skip them.
Fixes #894.

Skip debuginfo packages when running sonamecheck

---

rebasehelper/specfile.py
tests/test_specfile.py

The location was updated properly, but on a read-only object so the changes were thrown away.

Update paths to modified patches in rebased spec file
