rebase-helper/rebase-helper

rebasehelper/application.py
rebasehelper/patch_helper.py
rebasehelper/specfile.py

Minor issues

---

rebasehelper/archive.py

.asc file defined in Source directive is now downloaded properly.

Add .asc archive type to archive.py as dummy archive

---

rebasehelper/specfile.py

Fixes #166: Fix problem in case of troubles with parsing SPEC file.

---

rebasehelper/tests/test_utils.py
rebasehelper/utils.py

Remove local file if KeyboardInterrupt is raised during the download. Test is included.

Remove local file if KeyboardInterrupt is raised during the download. (fixes #189)

---

man/rebase-helper.1
rebasehelper/application.py
rebasehelper/cli.py
rebasehelper/output_tool.py
rebasehelper/settings.py
rebasehelper/tests/test_output_tool.py

This Pull Request introduce JSON support.
Reference issue #139

JSON support.

---

man/rebase-helper.1
rebasehelper/application.py
rebasehelper/cli.py
rebasehelper/tests/test_cli.py

This Pull Request fixes #152 
Please review it.
It includes also tests

Introduce --build-retries option

---

man/rebase-helper.1
rebasehelper/application.py
rebasehelper/checkers/abipkgdiff.py
rebasehelper/checkers/csmock.py
rebasehelper/checkers/pkgdiff.py
rebasehelper/checkers/rpmdiff.py
rebasehelper/cli.py
rebasehelper/exceptions.py
rebasehelper/output_tool.py
rebasehelper/tests/test_utils.py
rebasehelper/utils.py

Introduce csmock checker.

---

rebasehelper/utils.py

Fixes #201: Move information about checking size to debug.

---

rebasehelper/application.py
rebasehelper/checker.py
rebasehelper/tests/test_pkgdiff_checker.py
rebasehelper/utils.py

* this PR resolves issue #190 
* additional clean up, refactoring was done with the intention to increase the readability of code
* no functionality change is expected

Refactoring of Checker class and couple of other cleanups

---

rebasehelper/application.py
rebasehelper/cli.py
rebasehelper/constants.py
rebasehelper/logger.py
rebasehelper/tests/test_application.py

Catch exceptions and write traceback to debug log

---

rebasehelper/application.py
rebasehelper/build_helper.py
rebasehelper/cli.py
rebasehelper/tests/test_cli.py

Duplicated of PR #209 so that we can do a new release.

Add new option '--builder-options'

---

rebasehelper/application.py

Check the validity of the configuration at the beginning of Application.run()
Previously some checks were done late and some options were just ignored. If the combination of used options is not valid we fail now.
Signed-off-by: Tomas Hozza <thozza@redhat.com>

Check the validity of the configuration at the beginning of Application.run()

---

.landscape.yaml
pylintrc
rebasehelper/application.py
rebasehelper/build_log_analyzer.py
rebasehelper/specfile.py
rebasehelper/tests/test_utils.py
rebasehelper/utils.py

landscape.io cleanups

---

rebasehelper/application.py
rebasehelper/cli.py
rebasehelper/specfile.py
rebasehelper/tests/test_application.py

The PR should fixed the issues #241 
The old PR which I have closed is: https://github.com/rebase-helper/rebase-helper/pull/242

Fixes #241

---

rebasehelper/utils.py

Values provided in 19b94d1b46f7cae65a30b4898b62afb998223310 are used as
fallback.
Using system-provided values makes easies to re-use the generated spec.

Use name and e-mail from Git configuration if the value is configured

---

rebasehelper/specfile.py

False-positive detection of `cd` command caused `TestSpecFile.test_find_archive_target_in_prep` test to fail from time to time.

Make %prep section processing more robust

---

MANIFEST.in
rebasehelper/tests/test_git_helper.py
rebasehelper/utils.py

* Remove redundant line from `MANIFEST.in`
* Revert commit b9b9c5b
* Show error messages of `CoprRequestExceptions`

A few minor fixes

---

rebasehelper/application.py

Download both old and new sources.
Fixes #267

Download both old and new sources.

---

rebasehelper/application.py
rebasehelper/patch_helper.py
rebasehelper/utils.py

Only decode output of git commands if necessary

---

rebasehelper/application.py
rebasehelper/patch_helper.py

Prevent custom commit hooks from executing

---

rebasehelper/versioneers/anitya_versioneer.py

Handle missing versions in Anitya projects

---

rebasehelper/specfile.py
rebasehelper/tests/test_utils.py
rebasehelper/utils.py

In RPM < 4.13.90 level of some macros is decreased by 1, see:
https://github.com/rpm-software-management/rpm/commit/c4d41c30cecc910ada85d2fe4cbeab19673065d7

Fix RPM macro levels

---

.travis.yml

Improve the long line of the Travis script part.

Improve Travis script part by YAML block style "|".

---

Dockerfile
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/tests/test_utils.py
rebasehelper/utils.py
requirements.txt

Remove dependency on `hawkey` module which is to be deprecated.
Resolves #308.

Implement custom NEVRA parser

---

rebasehelper/application.py
rebasehelper/exceptions.py
rebasehelper/output_tool.py
rebasehelper/output_tools/json_output_tool.py
rebasehelper/output_tools/text_output_tool.py

RebaseHelperError exception now allows multiple
logs to be stored within it.
Resolves: #310

Allow multiple logs for RebaseHelperError

---

rebasehelper/versioneers/anitya_versioneer.py
rebasehelper/versioneers/pypi_versioneer.py

Try to find project using Anitya distro/package_name API first, if not found fallback to searching projects using pattern.
Anitya pattern API returns also projects whose name begins with desired package name.
Filter out such projects from the returned list.
Print useful error message when PyPI versioneer fails.
Resolves #315.
Resolves #318.

Fix Anitya and PyPI versioneer

---

doc-requirements.txt
docs/user_guide/installation.rst
rebasehelper/build_log_analyzer.py
rebasehelper/cli.py
rebasehelper/tests/test_cli.py
requirements.txt
setup.py
test-requirements.txt

* Add --version argument (as requested in #294)
* Remove useless messages shown after build log analysis (resolves #319)
* Fix `description` in `setup()`
* Move dependencies to `install_requires` in `setup()`

Several improvements

---

rebasehelper/checkers/rpmdiff_tool.py

Fix rpmdiff output

---

rebasehelper/tests/test_versioneer.py
rebasehelper/versioneers/npmjs_versioneer.py
setup.py

Added NPMJS versionner and test for it.
Resolves: #348

Add NPMJS Versioneer

---

rebasehelper/tests/test_versioneer.py
rebasehelper/versioneers/cpan_versioneer.py
setup.py

Add CPAN Versioneer

---

rebasehelper/build_helper.py

Fix processing of builder options

---

rebasehelper/application.py
rebasehelper/spec_hooks/ruby_helper.py
rebasehelper/specfile.py
rebasehelper/utils.py

Several rpm related changes and workarounds

---

rebasehelper/application.py

Sometimes the change to specfile is as easy as adding one line only.
The problem below can be fixed by adding the following to `%files` section:
```
%{_libdir}/fcitx/qt/libfcitx-quickphrase-editor5.so
```
Add option to pause between builds and modify the specfile used for new build in `rebased_sources`
Helps fixing this kind of errors with ease:
```
error: Installed (but unpackaged) file(s) found:
/usr/lib64/fcitx/qt/libfcitx-quickphrase-editor5.so
Installed (but unpackaged) file(s) found:
/usr/lib64/fcitx/qt/libfcitx-quickphrase-editor5.so
RPM build errors:
Child return code was: 1
```

Add option to make changes to specfile between builds

---

rebasehelper/checkers/rpmdiff_tool.py

Fix regexp in rpmdiff output analysis

---

rebasehelper/application.py

Remove ${version}-build directory after specfile modification

---

rebasehelper/spec_hooks/commit_hash_updater.py
rebasehelper/utils.py
rebasehelper/versioneers/anitya_versioneer.py
rebasehelper/versioneers/cpan_versioneer.py
rebasehelper/versioneers/npmjs_versioneer.py
rebasehelper/versioneers/pypi_versioneer.py
rebasehelper/versioneers/rubygems_versioneer.py

Handle ConnectionError when using requests

---

rebasehelper/application.py

Preserve changes done to rebased spec file before build retry

---

rebasehelper/application.py
rebasehelper/checker.py
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/checkers/csmock_tool.py
rebasehelper/checkers/pkgdiff_tool.py
rebasehelper/checkers/rpmdiff_tool.py

Add checkers category

---

rebasehelper/application.py
rebasehelper/checker.py
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/checkers/csmock_tool.py
rebasehelper/checkers/pkgdiff_tool.py
rebasehelper/checkers/rpmdiff_tool.py
rebasehelper/output_tool.py
rebasehelper/output_tools/text_output_tool.py
rebasehelper/patch_helper.py
rebasehelper/tests/test_output_tool.py

- Check output of ABIPkgDiff
- Implement format() method for each checker for better text output
- Add info about untouched patches to results
Resolves: #426, #378

Improve text output, check diffs output

---

Makefile
rebasehelper/specfile.py

* Do not perform cleanup before running Docker tests
* Expand macros before escaping version regexp

Miscellaneous fixes

---

docker/Dockerfile.base
rebasehelper/application.py
rebasehelper/options.py
rebasehelper/utils.py
setup.py

Also add upload functionality to `LookasideCacheHelper` to be able to upload new sources on update.
Resolves #463.

Add option to update "sources" file

---

rebasehelper/checker.py
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/checkers/csmock_tool.py
rebasehelper/checkers/pkgdiff_tool.py
rebasehelper/checkers/rpmdiff_tool.py
rebasehelper/output_tool.py

Check each checker for important info. Each checker decides what is important itself.

Iterate over checkers output

---

README.md

Extend README information about what useful output rebase-helper produces.

Extend README instructions

---

README.md
rebasehelper/application.py
rebasehelper/archive.py
rebasehelper/build_tools/mock_tool.py
rebasehelper/build_tools/rpmbuild_tool.py
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/checkers/pkgdiff_tool.py
rebasehelper/checkers/rpmdiff_tool.py
rebasehelper/cli.py
rebasehelper/constants.py
rebasehelper/logger.py
rebasehelper/options.py
rebasehelper/output_tool.py
rebasehelper/output_tools/text_output_tool.py
rebasehelper/patch_helper.py
rebasehelper/specfile.py
rebasehelper/srpm_build_tools/mock_tool.py
rebasehelper/srpm_build_tools/rpmbuild_tool.py
rebasehelper/utils.py

Add another verbosity level and create logs of different verbosity

---

rebasehelper/application.py
rebasehelper/build_tools/copr_tool.py
rebasehelper/build_tools/koji_tool.py
rebasehelper/build_tools/mock_tool.py
rebasehelper/build_tools/rpmbuild_tool.py
setup.py

Fix rebuilding

---

rebasehelper/application.py
rebasehelper/helpers/rpm_helper.py
rebasehelper/patch_helper.py
tox.ini

Fix pylint errors

---

rebasehelper/checker.py
rebasehelper/checkers/abipkgdiff_tool.py
rebasehelper/checkers/csmock_tool.py
rebasehelper/checkers/licensecheck_tool.py
rebasehelper/checkers/pkgdiff_tool.py
rebasehelper/checkers/rpmdiff_tool.py
rebasehelper/cli.py
rebasehelper/logger.py

Make checkers optional

---

rebasehelper/application.py
rebasehelper/helpers/koji_helper.py

Place RPMs from old build gathered from previous koji build
into the correct old-build/RPMS directory.
Fixes: #498
Signed-off-by: Sebastian Kisela <skisela@redhat.com>

Place RPMs from old build to correct directory

---

rebasehelper/checkers/rpmdiff_tool.py

Fix rpmdiff analysis

---

rebasehelper/specfile.py

Do not leave blank lines when removing patches from preamble

---

rebasehelper/build_tools/mock_tool.py
rebasehelper/build_tools/rpmbuild_tool.py
rebasehelper/spec_hooks/ruby_helper.py
rebasehelper/srpm_build_tools/mock_tool.py
rebasehelper/srpm_build_tools/rpmbuild_tool.py

* Fix incorrect use of SpecContent
* Fix populating list of logs on build failures

Multiple fixes

---

rebasehelper/helpers/koji_helper.py

This is useful not only for batch rebasing.

Try to get specific-version Koji build first

---

README.md

Link to the DevConf.cz 2016 video on Youtube.

README: link to video presentation

---

rebasehelper/patch_helper.py
rebasehelper/tests/functional/test_rebase.py
rebasehelper/tests/test_patch_helper.py
rebasehelper/tests/testing_files/patch_helper/1.patch
rebasehelper/tests/testing_files/patch_helper/2.patch
rebasehelper/tests/testing_files/patch_helper/3.patch
rebasehelper/tests/testing_files/patch_helper/4.patch
rebasehelper/tests/testing_files/patch_helper/lipsum_new.txt
rebasehelper/tests/testing_files/patch_helper/lipsum_old.txt

Should fix #566 and possibly #565.

Refactor GitPatchTool

---

rebasehelper/patch_helper.py

Detect unresolved conflicts after running mergetool

---

rebasehelper/specfile.py

Remove associated comments along with patches

---

rebasehelper/spec_hooks/escape_macros.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/test.spec
setup.py

Add spec hook for escaping macros in comments

---

rebasehelper/patch_helper.py

git since version 2.20 uses new rebase implementation and doesn't auto-skip empty commits anymore. Adapt to that.

Skip empty commits during rebase

---

rebasehelper/spec_hooks/replace_old_version.py
setup.py

Add spec hook for replacing old version string

---

rebasehelper/application.py

Log failed RPM and SRPM builds correctly

---

rebasehelper/plugins/build_log_hooks/files.py

- handle %global and %if keywords correctly
- follow Fedora Packaging Guidelines when adding manpages
Resolves: #629

Files build log hook fixes

---

tox.ini

Make the check only informative, do not fail if any issues are found.

Check also functions without type annotations using mypy

---

rebasehelper/application.py
rebasehelper/helpers/koji_helper.py
rebasehelper/patcher.py
rebasehelper/plugins/build_tools/rpm/mock.py
rebasehelper/plugins/build_tools/rpm/rpmbuild.py
rebasehelper/plugins/build_tools/srpm/mock.py
rebasehelper/plugins/build_tools/srpm/rpmbuild.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py

Minor SpecFile changes

---

rebasehelper/archive.py

Add support for Rust crates

---

rebasehelper/specfile.py

Sorry, forgot to include the addition in the previous PR

Add rust package category

---

rebasehelper/plugins/build_log_hooks/files.py

Specfile doesn't necessarly need to have the main %files section but it
can have other sections. Some specfiles don't have a %files section at
all, take this into account

Add more fallbacks for finding the best matching section

---

docs/_static/css/custom.css
docs/conf.py

Allow wrapping options in generated HTML documentation

---

rebasehelper/plugins/spec_hooks/replace_old_version.py
rebasehelper/tests/plugins/test_spec_hooks.py
rebasehelper/tests/testing_files/test.spec

Try to replace hardcoded version parts in Sources and Patches

---

rebasehelper/helpers/koji_helper.py

* Avoid constructing URLs manually, use `koji.PathInfo` class
* Use `getBuildLogs()` API method to get the list of logs

Reimplement KojiHelper.download_build()

---

rebasehelper/specfile.py

Found by Kamil over here: https://github.com/kdudka/nss-pem/pull/5#issuecomment-518192997

update_changelog: create %changelog if it doesn't exist

---

rebasehelper/plugins/checkers/sonamecheck.py
setup.py

Add sonamecheck

---

rebasehelper/application.py
rebasehelper/plugins/spec_hooks/commit_hash_updater.py
rebasehelper/specfile.py

Handle spec files without Source0

---

rebasehelper/plugins/checkers/__init__.py
rebasehelper/plugins/checkers/abipkgdiff.py
rebasehelper/plugins/checkers/sonamecheck.py

Implement detection of multiple SONAME changes

---

rebasehelper/helpers/copr_helper.py

Also prepare for the possibility of building in multiple chroots.

Migrate from legacy copr API to copr.v3

---

rebasehelper/application.py
rebasehelper/helpers/copr_helper.py
rebasehelper/plugins/build_tools/rpm/copr_.py

Resolves: #708 
Related issue: #461 (adds a mechanism for passing options to builders)

Add basic copr options

---

rebasehelper/helpers/rpm_helper.py
rebasehelper/plugins/spec_hooks/commit_hash_updater.py
rebasehelper/plugins/spec_hooks/pypi_url_fix.py
rebasehelper/plugins/spec_hooks/ruby_helper.py
rebasehelper/specfile.py
rebasehelper/tests/test_specfile.py
rebasehelper/tests/testing_files/test.spec
rebasehelper/types.py

Deal with conditionalized tags

---

rebasehelper/plugins/spec_hooks/replace_old_version.py
rebasehelper/tests/plugins/test_spec_hooks.py
rebasehelper/tests/testing_files/test.spec

Ignore dependency tags when replacing version

---

docs/api/helpers/bugzillahelper.rst
rebasehelper/cli.py
rebasehelper/helpers/bugzilla_helper.py
rebasehelper/options.py

Add option to rebase based on bugzilla ID

---

rebasehelper/tests/public_api/__init__.py
rebasehelper/tests/public_api/test_specfile.py
rebasehelper/tests/test_specfile.py

This covers most of packit's usage, I will add more tests later on but I want to avoid having an incredibly long PR

Add public API tests

---

rebasehelper/argument_parser.py

Suppress default help option in SilentArgumentParser

---

rebasehelper/plugins/spec_hooks/commit_hash_updater.py
rebasehelper/plugins/spec_hooks/ruby_helper.py
rebasehelper/specfile.py

Handle zero-padded indexes in Source and Patch tags and %patch macros

---

rebasehelper/plugins/spec_hooks/replace_old_version.py

ReplaceOldVersion fixes

---

rebasehelper/plugins/build_log_hooks/files.py
rebasehelper/spec_content.py

Add support for some new features of rpm 4.15

---

rebasehelper/helpers/lookaside_cache_helper.py

Related: https://github.com/packit-service/packit-service/issues/314

don't process sources if it's not a file

---

rebasehelper/plugins/checkers/abipkgdiff.py

Abipkgdiff changes

---

rebasehelper/specfile.py
rebasehelper/tests/conftest.py
rebasehelper/tests/test_specfile.py

Resolves: #622 (from what I can see, lists should now be fully functional and looking at the changelog there aren't any remaining features that we haven't implemented)

Update %patch indexes when using %patchlist

---

rebasehelper/plugins/spec_hooks/replace_old_version.py
rebasehelper/tests/plugins/test_spec_hooks.py

Automatically replace hardcoded extraversion

---

.packit.yml

https://packit.dev/docs/configuration/

Simplify packit config

---

rebasehelper/application.py
rebasehelper/helpers/koji_helper.py
rebasehelper/plugins/build_log_hooks/files.py
rebasehelper/plugins/build_tools/rpm/copr_.py
rebasehelper/plugins/checkers/abipkgdiff.py
rebasehelper/plugins/checkers/licensecheck.py
rebasehelper/plugins/checkers/pkgdiff.py
rebasehelper/plugins/checkers/rpmdiff.py
rebasehelper/plugins/checkers/sonamecheck.py
rebasehelper/plugins/plugin_manager.py
rebasehelper/results_store.py
rebasehelper/spec_content.py
rebasehelper/specfile.py
rebasehelper/temporary_environment.py

These issues were detected  by mypy with `--check-untyped-defs` argument.

Fix some typing issues detected by mypy

---

rebasehelper/helpers/lookaside_cache_helper.py

Fix unhandled exception in LookasideCacheHelper

---

rebasehelper/patcher.py

Use repository-local git configuration to store repository state, to be able to determine whether the repository was originally created by rebase-helper.

Deal with existing git repoository in extracted upstream sources

---

rebasehelper/application.py
rebasehelper/plugins/checkers/__init__.py
rebasehelper/plugins/checkers/abipkgdiff.py
rebasehelper/plugins/checkers/csmock.py
rebasehelper/plugins/checkers/licensecheck.py
rebasehelper/plugins/checkers/pkgdiff.py
rebasehelper/plugins/checkers/rpmdiff.py
rebasehelper/plugins/checkers/rpminspect_rpm.py
rebasehelper/plugins/checkers/rpminspect_srpm.py
rebasehelper/plugins/output_tools/text.py

- ordering by type in text report
- remove outputs of SRPM checkers when retrying the build

Checkers adjustments

---

rebasehelper/application.py

Renaming fix

---

rebasehelper/plugins/checkers/abipkgdiff.py
rebasehelper/tests/functional/test_rebase.py

Fallback to comparing without debuginfo if abipkgdiff can't read it

---

rebasehelper/argument_parser.py
rebasehelper/exceptions.py
rebasehelper/helpers/download_helper.py
rebasehelper/helpers/lookaside_cache_helper.py
rebasehelper/logger.py
rebasehelper/plugins/build_tools/__init__.py
rebasehelper/specfile.py

I'm not really sure about this. The requests still fail randomly with `Remote end closed connection without response`.
I'm still considering implementing the upload with `pycurl` after all, because it seems to work without issues.
Fixes #801.

Fix failing uploads to lookaside cache

---

rebasehelper/application.py
rebasehelper/options.py

Add --no-changelog-entry option

---

rebasehelper/application.py
rebasehelper/options.py
rebasehelper/specfile.py
rebasehelper/tests/public_api/test_specfile.py
rebasehelper/tests/test_specfile.py

Resolves: #826 
There is a problem with the tests, issue with macros seems to have appeared again (probably related to #811 )

Improve comment removal

---

rebasehelper/helpers/macro_helper.py

Suppress errors also when deleting macros

---

rebasehelper/patcher.py

There are patches with nonsensical paths that are still applicable using `patch` command. Sanitize such paths the way `patch` command does it to make such patches applicable with `git-apply`.
See for example:
https://src.fedoraproject.org/rpms/virtualbox-guest-additions/blob/ffb16faab29ea7bdd235ff859e6ab04e5c9b2bc1/f/0001-VBoxServiceAutoMount-Change-Linux-mount-code-to-use-.patch
https://src.fedoraproject.org/rpms/virtualbox-guest-additions/blob/ffb16faab29ea7bdd235ff859e6ab04e5c9b2bc1/f/VirtualBox-5.2.10-xclient.patch

Sanitize paths in patches before applying with git-apply

---

rebasehelper/specfile.py
rebasehelper/tests/public_api/test_specfile.py

Make it public and usable on its own, not only from within `SpecFile.write_updated_patches()`.

Refactor SpecFile._process_patches()

---

setup.py
test-requirements.txt

Make unidiff a regular requirement

---

CONTRIBUTING.md

Here's a file for new contributors. Obviously it's not (yet)
exhaustive, and starts with a few commansd I had to figure out
myself in order to contribute to rebase-helper.

CONTRIBUTING.md: Start a contributing file

---

containers/webhooks.py
rebasehelper/helpers/input_helper.py
setup.py

Resolves: https://github.com/rebase-helper/rebase-helper/issues/859

Replace soon-to-be deprecated distutils

---

rebasehelper/helpers/copr_helper.py

@nforro I didn't manage to reproduce the issue that you pointed out today, I tried building `vim-go` to avoid waiting for hours for the build to finish. I found a different problem - the responses from copr changed and the error is now in a dict-like structure so rebase-helper threw an error that the copr repository already exists and cannot be created while trying to build new packages.
I am not sure what's the better way to handle this - either we can parse the error (the current implementation in the PR) or just modify the if below (to `if 'You already have project named' in error:`). I like this approach a bit more as it is more "precise" and could give us some more options for error checking in the future if we need it.
As for the problem you messaged me about, could it have been a …

Update copr buildtool based on new copr responses

---

rebasehelper/plugins/build_log_hooks/files.py

In case of renames of files prepended by some directives such as %doc or
%license, we cannot automatically detect the rename. The directive
handles the installation of the file so removing the file makes rpmbuild
or mock not complain but the file is not there if it was renamed. This
can be common in case of renames such as README -> README.md. Warn the
user that this is happening and that it may be necessary to check the
specfile.
Signed-off-by: František Nečas <fnecas@redhat.com>

Warn the user about a potential rename

---

rebasehelper/helpers/macro_helper.py

Macros can have (and do have) multiline bodies. Account for that.

Fix parsing of %dump output

---

README.md
rebasehelper/helpers/macro_helper.py
rebasehelper/plugins/checkers/rpmdiff.py

Fix parsing issue in rpmdiff checker

---

doc-requirements.txt

https://readthedocs.org/projects/rebase-helper/builds/16406957/

Add workaround for broken documentation builds
